[package]
name = "soundboard_rs"
version = "0.1.0"
description = "Awesome soundboard app for streamers."
edition = "2024"

[dependencies]
global-hotkey = "0.8.0"
iced = "0.14.0"
iced_aw = "0.14.1"
iced_core = "0.14.0"
iced_widget = "0.14.2"
kbd = "0.2.1"
kbd-global = "0.2.1"
rfd = "0.17.2"
rodio = { version = "0.22.2", features = ["default"] }
serde = "1.0.229"
